DROP DATABASE IF EXISTS EnsinaFontes;

CREATE DATABASE IF NOT EXISTS EnsinaFontes;

USE EnsinaFontes;

CREATE TABLE IF NOT EXISTS  EnsinaFontes.books
(
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(30) NOT NULL,
	price DECIMAL(10, 2),
	author VARCHAR(100) NOT NULL,
	isbn VARCHAR(100),
	PRIMARY KEY(id)
);